import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito, Roboto_Mono } from "next/font/google";
import "./globals.css";
import GlobalProviders from "@/providers/globalProviders";
import * as S from "./layout.styles";
import Header from "@/components/layout/header/header";

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <GlobalProviders>
          <S.Container>
            <Header />
            <S.MainContainer>{children}</S.MainContainer>
          </S.Container>
        </GlobalProviders>
      </body>
    </html>
  );
}
